services:
  catalogdb:
    container_name: catalogdb
    image: postgres:18
    volumes:
      - postgres_catalog:/var/lib/postgresql
    restart: unless-stopped

  # catalogapi:
  #   container_name: catalogapi
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/CatalogAPI/Dockerfile
  #   depends_on:
  #     - catalogdb

volumes:
  postgres_catalog: